site_name: Data in H5
site_url: https://kyrylo-gr.github.io/dh5/
repo_url: https://github.com/kyrylo-gr/dh5
theme:
  name: material
  features:
    - navigation.instant
    - navigation.sections
    - search.suggest
    - search.highlight

plugins:
  - search
  - autorefs
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_options:
              returns_type_in_property_summary: true
            inherited_members: true
            filters:
              - '!^_' # exclude all members starting with _
              - '^__init__$' # but always include __init__ modules and methods
              - '^__new__$' # but always include __new__ methods
              - '^__getitem__$'
              - '^__setitem__$'
            show_source: true
            show_submodules: true
            show_root_heading: true
            show_root_toc_entry: false
            show_root_full_path: true
            show_object_full_path: false
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            docstring_style: google
            docstring_section_style: table
            members_order: source
            show_signature: true
            show_signature_annotations: false
            separate_signature: true
            unwrap_annotated: true
      watch: dh5/

nav:
  - About: about/
  - Releases: releases/
  # - Tutorials:
  #   - Examples: examples.md
  #   - Create and use variables: variables.md
  # - Developer's Guide:
  #   - Use mathematical expressions: expressions.md
  - Code Reference:
      - DH5: dh5
      - DataTypes: types/
      - For development: develop/
