name: documentation
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: Restore cache
        run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v3
        with:
          key: mkdocs-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-
      - run: pip install -r requirements-docs.txt
      - name: Build and deploy if push
        run: |
          if [ "${{ github.event_name }}" == "push" ]; then
            mkdocs gh-deploy --force
          else
            mkdocs build
          fi
